#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIVDMA_NUM_INSTANCES 1

/* Definitions for peripheral AXI_VDMA_0 */
#define XPAR_AXI_VDMA_0_COMPATIBLE "xlnx,axi-vdma-6.3"
#define XPAR_AXI_VDMA_0_BASEADDR 0x44a10000
#define XPAR_AXI_VDMA_0_HIGHADDR 0x44a1ffff
#define XPAR_AXI_VDMA_0_NUM_FSTORES 0x3
#define XPAR_AXI_VDMA_0_INCLUDE_MM2S 0x1
#define XPAR_AXI_VDMA_0_INCLUDE_MM2S_DRE 0x0
#define XPAR_AXI_VDMA_0_MM2S_DATA_WIDTH 0x40
#define XPAR_AXI_VDMA_0_INCLUDE_S2MM 0x1
#define XPAR_AXI_VDMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_AXI_VDMA_0_S2MM_DATA_WIDTH 0x80
#define XPAR_AXI_VDMA_0_INCLUDE_SG 0x0
#define XPAR_AXI_VDMA_0_ENABLE_VIDPARAM_READS 0x1
#define XPAR_AXI_VDMA_0_FLUSH_FSYNC 0x1
#define XPAR_AXI_VDMA_0_FLUSH_ON_FSYNC 0x1
#define XPAR_AXI_VDMA_0_MM2S_LINEBUFFER_DEPTH 0x200
#define XPAR_AXI_VDMA_0_S2MM_LINEBUFFER_DEPTH 0x200
#define XPAR_AXI_VDMA_0_MM2S_GENLOCK_MODE 0x3
#define XPAR_AXI_VDMA_0_S2MM_GENLOCK_MODE 0x2
#define XPAR_AXI_VDMA_0_INCLUDE_INTERNAL_GENLOCK 0x1
#define XPAR_AXI_VDMA_0_S2MM_SOF_ENABLE 0x1
#define XPAR_AXI_VDMA_0_MM2S_TDATA_WIDTH 0x20
#define XPAR_AXI_VDMA_0_S2MM_DATA_WIDTH 0x80
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_1 0x0
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_5 0x0
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_6 0x1
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_7 0x1
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_9 0x0
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_13 0x0
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_14 0x1
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_15 0x1
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_ALL 0x0
#define XPAR_AXI_VDMA_0_ADDRWIDTH 0x20
#define XPAR_AXI_VDMA_0_ENABLE_VERT_FLIP 0x0

/* Canonical definitions for peripheral AXI_VDMA_0 */
#define XPAR_XAXIVDMA_0_BASEADDR 0x44a10000
#define XPAR_XAXIVDMA_0_HIGHADDR 0x44a1ffff
#define XPAR_XAXIVDMA_0_ADDRWIDTH 0x20
#define XPAR_XAXIVDMA_0_COMPATIBLE "xlnx,axi-vdma-6.3"
#define XPAR_XAXIVDMA_0_ENABLE_VIDPARAM_READS 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_1 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_5 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_6 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_7 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_9 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_13 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_14 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_15 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_ALL 0x0
#define XPAR_XAXIVDMA_0_ENABLE_VERT_FLIP 0x0
#define XPAR_XAXIVDMA_0_FLUSH_FSYNC 0x1
#define XPAR_XAXIVDMA_0_FLUSH_ON_FSYNC 0x1
#define XPAR_XAXIVDMA_0_INCLUDE_MM2S 0x1
#define XPAR_XAXIVDMA_0_INCLUDE_MM2S_DRE 0x0
#define XPAR_XAXIVDMA_0_INCLUDE_S2MM 0x1
#define XPAR_XAXIVDMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIVDMA_0_INCLUDE_SG 0x0
#define XPAR_XAXIVDMA_0_INCLUDE_INTERNAL_GENLOCK 0x1
#define XPAR_XAXIVDMA_0_MM2S_DATA_WIDTH 0x40
#define XPAR_XAXIVDMA_0_MM2S_LINEBUFFER_DEPTH 0x200
#define XPAR_XAXIVDMA_0_MM2S_GENLOCK_MODE 0x3
#define XPAR_XAXIVDMA_0_MM2S_TDATA_WIDTH 0x20
#define XPAR_XAXIVDMA_0_NUM_FSTORES 0x3
#define XPAR_XAXIVDMA_0_S2MM_DATA_WIDTH 0x80
#define XPAR_XAXIVDMA_0_S2MM_LINEBUFFER_DEPTH 0x200
#define XPAR_XAXIVDMA_0_S2MM_GENLOCK_MODE 0x2
#define XPAR_XAXIVDMA_0_S2MM_SOF_ENABLE 0x1

#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_0_IS_DUAL 0x0
#define XPAR_AXI_GPIO_0_INTERRUPTS 0x2000
#define XPAR_FABRIC_AXI_GPIO_0_INTR 0
#define XPAR_AXI_GPIO_0_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x13

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_FABRIC_XGPIO_0_INTR 0
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x13
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x0
#define XPAR_XGPIO_0_INTERRUPTS 0x2000
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0x2
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x2
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a00000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a0ffff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x3
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x8
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x0
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x10
#define XPAR_AXI_QUAD_SPI_0_INTERRUPTS 0x1
#define XPAR_FABRIC_AXI_QUAD_SPI_0_INTR 1
#define XPAR_AXI_QUAD_SPI_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a00000
#define XPAR_FABRIC_XSPI_0_INTR 1
#define XPAR_XSPI_0_HIGHADDR 0x44a0ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x8
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x10
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_INTERRUPTS 0x1
#define XPAR_XSPI_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_0_NUM_SS_BITS 0x3
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x0
#define XPAR_XSPI_0_STARTUP_BLOCK 0x0
#define XPAR_XSPI_0_XIP_MODE 0x0

/* Definitions for peripheral M_AVALON_0 */
#define XPAR_M_AVALON_0_BASEADDR 0x44a20000
#define XPAR_M_AVALON_0_HIGHADDR 0x44a2ffff

/* Canonical definitions for peripheral M_AVALON_0 */
#define XPAR_M_AVALON_0_0_BASEADDR 0x44a20000
#define XPAR_M_AVALON_0_0_HIGHADDR 0x44a2ffff

/* Definitions for peripheral M_AVALON_1 */
#define XPAR_M_AVALON_1_BASEADDR 0x44a30000
#define XPAR_M_AVALON_1_HIGHADDR 0x44a3ffff

/* Canonical definitions for peripheral M_AVALON_1 */
#define XPAR_M_AVALON_1_0_BASEADDR 0x44a30000
#define XPAR_M_AVALON_1_0_HIGHADDR 0x44a3ffff

/*  BOARD definition */
#define XPS_BOARD_XEM8320-AU25P_SZG_PORT_F_SZG_PCIEX4_SZG_PORT_TXR4

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x7fff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 1
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "xcau25p"

#endif  /* end of protection macro */